# Generated by Django 3.0.1 on 2021-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210628_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('celular', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Eléctronico')),
                ('lugar', models.CharField(blank=True, max_length=50, null=True, verbose_name='lugar')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
