# Generated by Django 3.0.1 on 2021-06-21 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria  ',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=50, verbose_name='Nombre de tu negocio')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('phone', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('pais', models.CharField(max_length=30, verbose_name='País')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('mision', models.TextField(blank=True, null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Visión')),
                ('imagen', models.ImageField(blank=True, help_text='Adjunte una imagen del producto', null=True, upload_to='img_negocios', verbose_name='Imagen de portada')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Categoria')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='ClientePerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ClientePerfil',
                'verbose_name_plural': 'ClientePerfils',
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripción', models.TextField()),
                ('imagen', models.ImageField(blank=True, help_text='Adjunte una imagen del producto', null=True, upload_to='img_productos', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Negocio')),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
            },
        ),
    ]
