# Generated by Django 3.0.1 on 2021-08-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, help_text='Adjunte una imagen del producto', null=True, upload_to='img_productos', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria  ',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cuidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidad', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Cuidad',
                'verbose_name_plural': 'Cuidads',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=50, verbose_name='Nombre de tu negocio')),
                ('descripcion', models.TextField(help_text='Escriba una descripción de que trata.?')),
                ('direccion', models.CharField(help_text='Ejem. Av. Panamericana #590 Zona Sur', max_length=50, verbose_name='Dirección ')),
                ('celular', models.PositiveIntegerField(verbose_name='Num. de Celular')),
                ('pais', models.CharField(blank=True, max_length=30, null=True, verbose_name='País')),
                ('mision', models.TextField(blank=True, null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Visión')),
                ('imagen', models.ImageField(blank=True, help_text='Adjunte una imagen del producto', null=True, upload_to='img_negocios', verbose_name='Imagen de portada')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordens',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Catalogo')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
