# Generated by Django 3.0.1 on 2021-06-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='phone',
        ),
        migrations.AddField(
            model_name='negocio',
            name='descripcion',
            field=models.TextField(default='negocio de venta', help_text='Escriba una descripción de que trata.?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negocio',
            name='ciudad',
            field=models.CharField(help_text='Pais - Ciudad', max_length=150, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(help_text='Ejem. Av. Panamericana #590 Zona Sur', max_length=50, verbose_name='Dirección '),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='pais',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='País'),
        ),
    ]
