# Generated by Django 3.0.1 on 2021-06-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_negocio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='user',
        ),
        migrations.AlterField(
            model_name='clienteperfil',
            name='celular',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='phone',
            field=models.PositiveIntegerField(unique=True, verbose_name='Num. de Celular'),
        ),
    ]
