# Generated by Django 3.0.1 on 2021-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_negocio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='precio',
            field=models.FloatField(default='5'),
            preserve_default=False,
        ),
    ]
