# Generated by Django 3.0.1 on 2021-07-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_catalogo_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
