# Generated by Django 3.0.1 on 2021-07-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='celular',
            field=models.PositiveIntegerField(verbose_name='Tu Número de WhatsApp'),
        ),
    ]
