# Generated by Django 3.0.1 on 2021-07-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20210710_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='celular',
            field=models.PositiveIntegerField(default='79436914', verbose_name='Num. de Celular'),
            preserve_default=False,
        ),
    ]
