# Generated by Django 3.0.1 on 2021-07-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_pedido_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='business.Catalogo'),
            preserve_default=False,
        ),
    ]
